package app.yberm.main;

/**
 *
 * @author Yber-M;
 */
public class frmMenu extends javax.swing.JFrame {

    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnComprobante = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnPromociones = new javax.swing.JButton();
        btnDescuentos = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(36, 49, 94));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComprobante.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnComprobante.setText("COMPROBANTE DE PAGO");
        pnlMenu.add(btnComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 320, 70));

        btnServicios.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnServicios.setText("SERVICIOS");
        pnlMenu.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 320, 70));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Diario Jornada(CRUD)");
        pnlMenu.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnPromociones.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnPromociones.setText("PROMOCIONES");
        pnlMenu.add(btnPromociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 320, 70));

        btnDescuentos.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnDescuentos.setText("DESCUENTOS");
        pnlMenu.add(btnDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 320, 70));

        btnEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnEmpleado.setText("EMPLEADO");
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });
        pnlMenu.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 320, 70));

        btnCliente.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCliente.setText("CLIENTE");
        pnlMenu.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 320, 70));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        frmEmpleado frmEmpl = new frmEmpleado();

        frmEmpl.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnComprobante;
    private javax.swing.JButton btnDescuentos;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnPromociones;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
